export default {
    title: 'The Project',
    'placeholder': 'Projeto Mil Folhas',

    'content1': `22º27'32.78" S    43º12'43.35" W   (Alt. 800 a 950m)`,

    'content2': `O Projeto Mil Folhas começou em 1996, para reflorestar uma área pública de aproximadamente 200.000 m2 (50 ha) entre os km 71 e 73 da rodovia interestadual BR-040 no Vale Florido em Petrópolis, estado do Rio de Janeiro, Brasil. A área, originalmente coberta por uma densa floresta de Mata Atlântica de altitude, foi completamente, e desnecessariamente desmatada pelo DNER (Departamento Nacional de Estradas de Rodagem) em meados dos anos 1970 durante as obras de duplicação da antiga Estrada do Contorno.`,

    'content3': `O projeto foi a iniciativa de dois amigos, Guga Casari e Chico Bicalho, em recompor a área cujo solo de encostas estava muito degradado, coberto apenas por capins braquiária, gordura e colonião, e sofrendo com frequentes incêndios e muitas erosões, já que havia sido privado de sua cobertura florestal por mais de vinte anos.`,

    'content4': `No começo, o projeto foi executado de maneira informal, com a mobilização de amigos e moradores da região, em mutirões que nem sempre surtiam o efeito desejado. Mesmo que as técnicas utilizadas, baseadas no sistema de Sucessão Secundária, aprimoradas pelo saudoso prof. Paulo Kageyama fossem teoricamente corretas, o projeto evoluiu lentamente nos primeiros anos, com pouco dinheiro, e a falta de conhecimento em fertilização. O solo estava tão degradado e desprovido de nutrientes, que nós não sabíamos como dosar os fertilizantes corretamente, ora usando muita, ora usando pouca quantidade, e nem sempre misturando as fórmulas corretas para cada aplicação.`,

    'content5': `Depois de atender a congressos de botânica, e de muito estudar, Chico Bicalho (que não é biólogo) constatou em meados dos anos 1990, que não havia um texto único disponível sobre reflorestamento com espécies da Mata Atlântica nos anais da agronomia no Brasil, que fragmentados em diversos papéis, formavam um dado de informações que precisava ser montado como um quebra-cabeças. E por causa disso, colher dados científicos e técnicos para uma pessoa que não era bióloga ou agrônoma era muito difícil. `,

    'content6': `Portanto, um manual de reflorestamento foi criado com a ajuda de inúmeras pessoas, principalmente Paulo Kageyama, Maria Lúcia Nova da Costa, Tamar Bajgielman, Leonardo Ciuffo Faver, e Orlando Graeff. Esse manual é muito útil para ajudar qualquer pessoa a reflorestar; é um texto muito técnico e detalhado, mas escrito de maneira simples e direta, colhido de informação acadêmica e baseado no nosso aprendizado durante o projeto, aprimorado durante mais de quinze anos de pesquisa e trabalho no campo. Esse manual explica cada detalhe de como desenvolver um projeto de reflorestamento, e está incluído nesse site.`,

    'content7': `Um manual de reflorestamento teria feito uma diferença enorme nos primeiros anos do projeto, porque não só o caminho teria sido facilitado, acelerando o resultado do trabalho como um todo, mas o processo inteiro teria sido muito menos custoso, mais eficiente e objetivo. Esperamos que esse manual facilite a vida de muitos grupos interessados em reflorestar com espécies da Mata Atlântica.`,

    'content8': `Em 2001, Guga Casari e Chico Bicalho, inventaram um brinquedo chamado ZéCar, distribuído pela empresa Kikkerland Design Inc. de Nova York, ficando estabelecido que os royalties decorrentes da venda desse produto iriam integralmente para o Projeto Mil Folhas. Logo em seguida, um generoso matching fund da Kikkerland Design, dobrou a verba para o projeto, aumentando muito a nossa capacidade de plantio. Desde de então, o projeto recebeu mais de 320 mil árvores, de pelo menos 150 espécies nativas da Mata Atlântica.`,

    'content9': `Desde o ano 2000, o projeto trabalha com alunos da Escola Municipal João Kopke na Fazenda Inglesa, Petrópolis, em dias de consciência ambiental, feitos por grupos com mais de 350 alunos de todas as idades, colaborando para a conscientização de toda a população local sobre a importância do meio ambiente, e a preservação da natureza. Uma vez por ano, os alunos da E. M. João Kopke fazem uma caminhada de 3.5 km da escola até o local de plantio, retirando o lixo na estrada, distribuindo placas com frases sobre a preservação do meio ambiente, e culminando com o plantio de aproximadamente 1.500 árvores. Um dos mais importantes aspectos do projeto é a educação de base voltada para o meio ambiente, e a conscientização ambiental para todos os moradores da região.`,

    'content10': `O Projeto Mil Folhas, por estar adjacente a duas grandes reservas florestais de Mata Atlântica, a Reserva Biológica de Araras (2.000 ha), e a Reserva Biológica do Tinguá (26.000 ha), se adaptou rapidamente ao ambiente florestal, agindo como um corredor de vegetação entre essas duas importantes reservas biológicas. O projeto também é berçário de mudas com matrizes de várias espécies importantes de arvores raras da Mata Atlântica que foram plantadas, e muitas já frutificando, como o Palmito jussara (Euterpe edulis), Peroba-de-Campos (Paratecoma peroba), Cambucá (Marlierea edulis), Jequitibá (Cariniana estrellensis), Araucaria (Araucaria angustifolia), Jatobá (Hymenaea courbaril) entre várias outras.`,

    'content11': `TO projeto completou 20 anos em 2016, e a despeito das dificuldades iniciais, obteve progressos anuais impressionantes, quando uma média de 35 a 37 mil mudas foram plantadas todo ano entre 2004 e 2009. Até agora, mais de 325 mil mudas de espécies nativas do bioma da Mata Atlântica de mais de 150 espécies diferentes já foram plantadas. Além de reflorestar e educar, o Projeto Mil Folhas estabeleceu um banco genético de plantas, formando uma matriz riquíssima para a coleta de sementes para que novos projetos de reflorestamento possam ser implantados. Nós queremos ser exemplo, e ajuda, para que muitas pessoas mais plantem florestas por todo o Brasil.`,

    'content12': `Esse projeto é dedicado, com amor, à Philip e Molly Jenkins.`,
    
    'Go to page 2': 'Go to page 2',
};
