export default {
  title: 'Tools',
  'placeholder': 'Ferramentas',
  // add other fields

  'content1': `Usar as ferramentas certas, e manter essas ferramentas em bom funcionamento faz toda a diferença do mundo para se trabalhar com eficiência num projeto de reflorestamento de grande escala. Boas ferramentas otimizam o nosso o esforço, e geram melhores resultados no campo com o mínimo de desperdício em energia física para que a produção de um dia no trabalho pesado seja mais eficiente e menos cansativa.`,
  'content2': `Acidentes devem ser evitados a todo custo, isso porque com o cansaço, qualquer distração pode provocar sérias consequências, principalmente quando se trabalha com ferramentas de corte movidas a gasolina como as roçadeiras, que são muito importantes em um projeto de reflorestamento. Uma simples cavadeira pode causar ferimentos graves quando manuseada de maneira incorreta ou desleixada. O operador de uma roçadeira deve sempre usar botas de couro, caneleiras, luvas de couro, óculos de proteção e protetores de ouvido, e jamais usar a roçadeira se estiver cansado, doente ou de ressaca. O Projeto Mil Folhas possui duas Husqvarna 143R, que são excelentes roçadeiras.`,
  'content3': `É importante que as cavadeiras, enxadas, pás, trados, facões, lâminas de roçadeira ou foices sejam mantidas limpas e com suas lâminas sempre afiadas, por isso, uma boa lima chata de corte simples com mais ou menos 150 a 200 mm, deve estar sempre junto as ferramentas, e todo momento de descanso deve ser aproveitado para afiar as ferramentas de trabalho, limando sempre em uma direção, sentindo a lima "morder" o metal. Uma ferramenta afiada, seja ela uma enxada, ou cavadeira, é uma ferramenta mais eficiente, e que cansa muito menos.`,
  'content4': `Uma bomba d'água de boa qualidade pode ser muito útil. O Projeto possui uma bomba Stihl P835 com entradas para mangueiras de 1" com 10 m de mangueiras de alta pressão para a entrada de água, que pode ser de um riacho ou poço, e mais 10 m de mangueira de 1" para a saída da água com uma redução para mangueiras de 3/4" de alta pressão e uniões para outras mangueiras que podem ser tanto de 3/4" ou de 1/2". No projeto já levamos mangueiras a mais de 120 m da fonte de água bombeada com muita pressão.`,
  'content5': `Os recipientes de combustível para a bomba d'água e para a roçadeira devem ser no tamanho apropriado para um dia de uso, pois não adianta levar mais do que é preciso. A mistura de óleo 2 tempos deve ser feita na noite anterior, na quantidade exata recomendada pelo fabricante, e com óleo de boa qualidade. Nós usamos o Castrol Super TT, ou Motul 710 2T. É importante fazer a manutenção dos motores e outros componentes rigorosamente, e manter os filtros de ar sempre limpos e intactos, sobretudo é importante não forçar demais os motores 2 tempos, principalmente em dias muito quentes.  Uma boa engraxadeira com graxa de qualidade deve ser parte do kit da roçadeira, e todos os pinos devem ser engraxados após um dia de muito uso da máquina.`,
  'content6': `Uma mochila de tamanho médio é conveniente para levar ferramentas da roçadeira ou bomba d'água, uma lima e um canivete suíço básico, luvas de couro, água (muita água), bananas, sanduiches, e algumas barrinhas energéticas. O canivete deve ter, além da lâmina, uma tesoura, e sobretudo uma pinça, que será útil para remover farpas. Um pano limpo e um pequeno frasco de álcool gel também devem estar na mochila junto com alguns Band-Aid, por razões óbvias.`,
  'content7': `As roupas, são critério de cada um, mas no Mil Folhas, os calçados para o verão são botas de borracha brancas, porque no sol de verão, elas esquentam os pés muito menos do que as botas pretas. Um chapéu de palha com aba grande, protege além da cabeça, os ombros e a nuca, e também usamos camisetas de algodão vermelhas, que aumentam a visualização no meio das plantas, facilitando achar uns aos outros, assim como calças compridas largas, tipo cargo com muitos bolsos, que funcionam bem.`,
  'content8': `Outras ferramentas importantes são as usadas no combate ao fogo. Procure o IEF (Instituto Estadual de Florestas) na sua região para saber como treinar uma brigada de incêndio florestal, mas essencialmente as duas ferramentas mais importantes são um abafador de fogo, feito com placas de borracha lonada e uma haste longa, e uma ferramenta que precisa ser adaptada que é um ancinho com uma enxada no lado de cima (2 em1) para remover folhas e galhos secos do caminho do fogo para outra pessoa abafar as chamas. Pesquise.`,
  'content9': `O porta iscas de formigas é outra peça de ferramenta importante, sobretudo nos meses de primavera (Set. Out. Nov.) durante os primeiros plantios, porque uma colônia de formigas cortadeiras pode arruinar o plantio de 3 mil mudas em apenas uma semana. Sentimos pena das formigas, mas quando a mata crescer, haverão muitas folhas disponíveis para elas, porém no começo, quando as mudas são muito pequenas elas podem fazer um enorme estrago. A MEC-Plant, além de diversos outros produtos, fabrica um porta iscas excelente, que basta ser colocado bem na trilha das formigas com as iscas dentro e elas fazem o resto.`,
  'content10': `Com o passar do tempo, as pessoas escolhem e trabalham com as ferramentas que funcionam melhor para cada aplicação, e com as quais se adaptam melhor. `,
  'url': ` https://mecplant.com.br/produto/porta-iscas/`,

  'hats': 'Botas De Borracha Brancas (Para O Verão), Chapéu De Palha Com Abas Largas, E Luvas De Couro São O Básico Para Um Dia De Trabalho No Campo. Lembrando Que O Operador Da Roçadeira Também Deve Usar Óculos De Proteção, Caneleiras, Botas De Couro, E Proteção De Ouvido.',
  'saws': 'Durante O Período De Manutenção Após O Plantio, Ferramentas De Corte Podem Ser Importantes Para Remover Parasitas Das Mudas, Lembrando Que Não É Necessário Fazer Nenhum Tipo De Poda, Caso Não Hajam Parasitas Como A Erva-De-Passarinho Por Exemplo. Do Alto, Um Podão De Haste Para Alcançar Pontos Mais Altos, Uma Serra De Haste E Uma Serra De Mão, Uma Tesoura De Poda (Ou Podão), E Um Facão.',

  'hand': `A Mão Humana É A Ferramenta Mais Eficiente, Mais Utilizada, E Sempre Disponível Para Um Projeto De Reflorestamento.`,
  'rocado': `Essa É A Maioria Das Ferramentas Usadas Para Roçar O Capim Alto. De Cima Para Baixo, Uma Vassoura De Jardim, Dois Tipos De Foices, E Uma Roçadeira À Gasolina. Essas Ferramentas São Fundamentais No Início De Todo O Projeto.`,
  'covando': `Existem Muitas Ferramentas Para Cavar E Abrir Covas, Cada Uma Tem Sua Função, E Dependem Do Gosto E Adaptação De Cada Pessoa Para O Trabalho. A Partir Do Alto, Dois Tipos De Picaretas, Que Ajudam Muito Em Solo Compactado, Uma Cavadeira Reta (A Favorita De Muita Gente), Uma Cavadeira Articulada (Que Entope Se A Terra Estiver Molhada Demais), Um Enxadão (Muito Popular) E Um Trado, Que Necessita De Muito Preparo Físico. Lembrando Que Essas Ferramentas Funcionam Melhor Sempre Que Suas Lâminas Estiverem Afiadas.`,
  'movendo': `Essas Ferramentas Muitas Vezes Trabalham Em Conjunto Com As Ferramentas Para Cavar, E Também Podem Ser Usadas Para Esse Fim. Mas, Principalmente, Elas São Utilizadas Para Mover Terra, Pedras, Pedaços De Raíz, E Entulho Em Geral. A Partir De Cima, Uma Pá Reta Que É Ideal Para Mover O Solo E Detritos, Uma Pá De Ponta Que Também É Útil Para Cavar, E Duas Enxadas Largas Com Ângulos Diferentes.  Essas Ferramentas Também São Muito Utilizadas Para Misturar Grandes Quantidades De Adubo Ou Fertilizantes. Lembrando Que Essas Ferramentas Funcionam Melhor Sempre Que Suas Lâminas Estiverem Afiadas.`,

  'pump': `Uma Bomba D'água De Alta Pressão À Gasolina Com Muitos Metros De Mangueiras De Alta Pressão É Uma Ferramenta Muito Importante Quando O Plantio É Feito Em Dias Sem Chuva.`,
  'file': `Uma Lima Chata De Corte Simples Com Mais Ou Menos 150 A 200 Mm É Essencial Para Manter As Ferramentas Afiadas, Sejam Elas Uma Enchada, Enchadão, Pá, Ou Cavadeira.`, 
  'greaser': `A Roçadeira Deve Sempre Ser Mantida Bem Lubrificada E Engraxada. Uma Boa Engraxadeira E Graxa De Qualidade São Importantes Para Manter A Roçadeira Em Boas Condições De Trabalho.`,
  'swiss': `Um Canivete Suíço Básico É Essencial.`, 
  'abafador': `Um Abafador De Fogo Feito Com Placas De Borracha E Uma Haste Longa Pode Ser Comprado Ou Fabricado Em Casa, Lembrando Que Essa, Dentre Todas As Ferramentas É A Que Precisa Do Peso E Ergonomia Corretos Para Cada Pessoa, Porque Ninguém Precisa Se Cansar Sem Necessidade No Meio Do Combate A Um Incêndio. Não Ha Necessidade De Uma Ferramenta Muito Grande Porque O Combate Ao Fogo É Extremamente Vigoroso E Muito Cansativo.`, 
  'rakehoe': `Uma Enxada/Ancinho É Uma Ferramenta Que Não Existe Para Vender No Brasil, Mas Pode Ser Adaptada. Ela É Essencial, Junto Com O Abafador, Para Remover Folhas Secas E Galhos Do Caminho Do Fogo Enquanto Outra Pessoa Usa O Abafador.`,
  'mec1':
    
    `O Porta Iscas Da Mec-Plant Funciona Perfeitamente Para Eliminar Formigas Cortadeiras Da Região Do Plantio, Mantendo As Iscas Sempre Secas. Basta Colocar As Iscas No Seu Interior, E Instalar A Peça No Caminho Das Formigas, Que Sobem Por Uma Pequena Rampa, Pegam As Iscas E Saem Por Outra Rampa.`,

 'mec2':
    
    `O Porta Iscas Da Mec-Plant Funciona Perfeitamente Para Eliminar Formigas Cortadeiras Da Região Do Plantio, Mantendo As Iscas Sempre Secas. Basta Colocar As Iscas No Seu Interior, E Instalar A Peça No Caminho Das Formigas, Que Sobem Por Uma Pequena Rampa, Pegam As Iscas E Saem Por Outra Rampa.`,

  'mec3':
    
    `O Porta Iscas Da Mec-Plant Funciona Perfeitamente Para Eliminar Formigas Cortadeiras Da Região Do Plantio, Mantendo As Iscas Sempre Secas. Basta Colocar As Iscas No Seu Interior, E Instalar A Peça No Caminho Das Formigas, Que Sobem Por Uma Pequena Rampa, Pegam As Iscas E Saem Por Outra Rampa.`,
    
  
   
  };
